# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_remove_shifts_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runs',
            name='run_count',
        ),
        migrations.AddField(
            model_name='runs',
            name='runs_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
