# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_auto_20171121_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
