# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_groupshift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupshift',
            old_name='end_datetime',
            new_name='week_day',
        ),
        migrations.RemoveField(
            model_name='groupshift',
            name='start_datetime',
        ),
    ]
