# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_auto_20171109_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runs',
            old_name='runs_time',
            new_name='runs_end',
        ),
        migrations.AddField(
            model_name='runs',
            name='runs_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
