# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_auto_20171116_0503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Runs',
            new_name='Run',
        ),
    ]
